version: "3.7"
services:

  montyexchangemicroservice:
    image: kaytho/monty:montyexchangemicroservice
    container_name: montyexchangemicroservice
    ports:
      - 9047:9047
    environment:
      - RABBIT_MQ_HOST=rabbitmq
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge

